name: Attach Artifact to Release

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:    

jobs:
  attach-artifact-to-release:
    uses: liquibase/build-logic/.github/workflows/extension-attach-artifact-release.yml@main
    secrets: inherit
