name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize


jobs:
  build-test:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
    secrets: inherit

  dependabot-automerge:
    needs: build-test
    uses: liquibase/build-logic/.github/workflows/dependabot-automerge.yml@main
    secrets: inherit
